security:
    encoders:
        # Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 4
    providers:
        our_database_users:
            entity: { class: UserBundle:User }
        # in_memory:
            # memory:
                # users:
                    # mikedfunk:
                        # password: 123
                        # roles: 'ROLE_USER'
                    # admin:
                        # password: $2a$12$cyTWeE9kpq1PjqKFiWUZFuCRPwVyAZwm4XzMZ1qPUFl7/flCM3V0G
                        # roles: 'ROLE_ADMIN'

    firewalls:
        # dev:
            # pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            # security: false
        secured_area:
            remember_me:
                key: "secret key"
            pattern: ^/
            form_login:
                check_path: login_check
                login_path: login_form
            logout:
                path: logout
                target: login_form
            anonymous: ~
        # default:
            # anonymous: ~
    access_control:
        # moving security to controller class
        # - { path: ^/new, roles: ROLE_USER }
        # - { path: ^/create, roles: ROLE_USER }
